# Generated by Django 3.0.3 on 2020-03-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectviewed',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
