# Generated by Django 3.0.3 on 2020-03-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='update',
            new_name='updated',
        ),
    ]
