# Generated by Django 3.0.3 on 2020-03-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.TextField()),
                ('author_name', models.TextField()),
                ('book_cover', models.ImageField(upload_to='books_cover')),
                ('book_content', models.FileField(upload_to='books_pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('content', models.TextField()),
            ],
        ),
    ]
