# Generated by Django 3.0.3 on 2020-03-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0002_auto_20200306_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=100),
        ),
    ]
