# Generated by Django 3.0.3 on 2020-03-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylibrary',
            old_name='books',
            new_name='products',
        ),
        migrations.AddField(
            model_name='mylibrary',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
