# Generated by Django 3.0.3 on 2020-03-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0006_auto_20200312_0143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectViewed',
        ),
    ]
